[ui]
add_api_endpoint = "Add API endpoint"
add_api_endpoint_shortcut = " (e)"
theme_label = "Theme: "
theme_shortcut = " (t)"
api_endpoint_name_prompt = "API endpoint name:"
input_cursor = "_"
settings_title = "Settings"
settings_shortcut = " (s)"
theme_setting = "Theme"
language_setting = "Change Language"
close_dialog = "Close"
language_dialog_title = "Select Language"
language_search_placeholder = "Search languages..."
no_languages_found = "No languages found"
new_app_dialog_title = "No Rext app found"
new_app_dialog_prompt = "Create a new Rext app?"

[messages]
quit_instruction_prefix = "Press "
quit_instruction_middle = " or "
quit_instruction_suffix = " to quit"
settings_instruction = "Use arrow keys to navigate, Enter to select, Esc to close"
language_instruction = "Type to search, use arrow keys to navigate, Enter to select"

[keys]
add_endpoint = "e"
toggle_theme = "t"
settings = "s"
quit = "q"
quit_combo = "Ctrl+C"
escape = "Esc"
enter = "Enter"
backspace = "Backspace"
up = "Up"
down = "Down"