[ui]
add_api_endpoint = "Add API endpoint"
add_api_endpoint_shortcut = " (e)"
generate_sea_orm_entities = "Generate SeaORM Entities"
generate_sea_orm_entities_shortcut = " (g)"
theme_label = "Theme: "
theme_shortcut = " (t)"
api_endpoint_name_prompt = "API endpoint name:"
input_cursor = "_"
settings_title = "Settings"
settings_shortcut = " (s)"
theme_setting = "Theme"
language_setting = "Change Language"
close_dialog = "Close"
language_dialog_title = "Select Language"
language_search_placeholder = "Search languages..."
no_languages_found = "No languages found"
new_app_dialog_title = "Rext Scaffold Tool"
new_app_no_app_detected = "No Rext app detected."
new_app_dialog_prompt = "Would you like to create a new Rext app?"
new_app_create_button = "Create"
new_app_cancel_button = "Cancel"
new_app_success_message = "Your Rext app is ready in {dir_name}, use Esc to close this"
new_app_error_message = "There was a problem building the Rext app in {dir_name}"
destroy_app_setting = "Destory Rext app"

[messages]
quit_instruction_prefix = "Press "
quit_instruction_middle = " or "
quit_instruction_suffix = " to quit"
settings_instruction = "Use arrow keys to navigate, Enter to select, Esc to close"
language_instruction = "Type to search, use arrow keys to navigate, Enter to select"
new_app_instruction = "Use arrow keys to select, Enter to confirm"
destroy_app_success = "Successfully dismantled the Rext app in {dir_name}"
destroy_app_error = "An error ocurred dismantling the Rext app: {error}"

[keys]
add_endpoint = "e"
generate_sea_orm_entities_with_open_api_schema = "g"
toggle_theme = "t"
settings = "s"
quit = "q"
quit_combo = "Ctrl+C"
escape = "Esc"
enter = "Enter"
backspace = "Backspace"
up = "Up"
down = "Down"
left = "Left"
right = "Right"
