[ui]
add_api_endpoint = "Ajouter un endpoint API"
add_api_endpoint_shortcut = " (a)"
theme_label = "Thème: "
theme_shortcut = " (t)"
api_endpoint_name_prompt = "Nom de l'endpoint API:"
input_cursor = "_"
settings_title = "Paramètres"
settings_shortcut = " (s)"
theme_setting = "Thème"
language_setting = "Changer de langue"
close_dialog = "Fermer"
language_dialog_title = "Sélectionner une langue"
language_search_placeholder = "Rechercher des langues..."
no_languages_found = "Aucune langue trouvée"

[messages]
quit_instruction_prefix = "Appuyez sur "
quit_instruction_middle = " ou "
quit_instruction_suffix = " pour quitter"
settings_instruction = "Utilisez les flèches pour naviguer, Entrée pour sélectionner, Échap pour fermer"
language_instruction = "Tapez pour rechercher, utilisez les flèches pour naviguer, Entrée pour sélectionner"

[keys]
add_endpoint = "a"
toggle_theme = "t"
settings = "s"
quit = "q"
quit_combo = "Ctrl+C"
escape = "Esc"
enter = "Enter"
backspace = "Backspace"
up = "Up"
down = "Down"